name: Terraform and Java App Deployment

on:
  push:
    branches:
      - feature1

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: |
          terraform apply -auto-approve << EOF
          yes
          EOF
          az_web_app_name=$(terraform output -raw azure_web_app_name)
        id: terraform

  deploy_java_app:
    runs-on: ubuntu-latest
    needs: terraform
    if: ${{ needs.terraform.result == 'success' }}

   steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Change to project directory
        run: cd java_app_on_azure_devops_task  # Replace 'java_app_on_azure_devops_task' with your repository name

      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '1.8'

      - name: Build with Maven
        run: |
          mvn clean install -f java_app_on_azure_devops_task/pom.xml
          cd java_app_on_azure_devops_task/target  # Change to target directory where JAR file is generated
          ls -la  # List files in the directory for verification purposes

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: java-app
          path: '${{ github.workspace }}/target/*.jar'

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ steps.terraform.outputs.azure_web_app_name }}
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_D22C4CDE61E3434EA952E27D09520BD4 }}
          package: '*.jar'
